### ISSUE TITLE
pip install cli not functional.

### ISSUE THREAD

**Issue by Nikoleta-v3** [ArcasProject/Arcas#20]
A issue  for using cli after pip install arcas.

**Comment by Nikoleta-v3** [comment]
The script is saved as `arcas_scrape`. Python does not execute it because it does not recognised as a python script. There are two ways to fix this:

**1. Add line**
We can either add this line `#!/usr/bin/env python` in the beginning of the script

or

**2. Rename**
Rename `arcas_scrape` to `arcas_scrape.py`. Though if renamed the cli command will be

          >>>  arcas_scrape.py -p ieee -a Glynatsi

**Comment by drvinceknight** [comment]
I'd go with adding the line at the top. It's common.
