### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Nikoleta-v3** [ArcasProject/Arcas#29]
Reading  a few thoughts on how a proper Readme should look I suggest a few alterations.

- add a few examples on pinging APIs
- add a few things on analysing the meta data
- add icons
- link to Documentation for further information

**Comment by drvinceknight** [comment]
Can you point me at what you've read? We've been talking about the Axelrod
README on https://github.com/Axelrod-Python/Axelrod/issues/1047

**Comment by Nikoleta-v3** [comment]
I was reading Axelrod's issue actually.

**Comment by Nikoleta-v3** [comment]
If I came across a good link/guide I will make sure to share

**Comment by drvinceknight** [comment]
https://stackoverflow.com/questions/2304863/how-to-write-a-good-readme
