### ISSUE TITLE
Different Readthedocs/latest and pip version

### ISSUE THREAD

**Issue by ilyasst** [ArcasProject/Arcas#60]
Hello,

I was able to access the open_access column from my Arxiv dataframe after downloading arcas from pip. It seems like the current Master version is not the same as the one available through pip and that the documentation is for the Github version, not the pip one.
This was confusing for me as I could not reproduce parts of the documentation.

Thank you for your work,
Cheers,
ilyass

**Comment by Nikoleta-v3** [comment]
Hello @ilyasst,

Thank you very much for your issue. 

You are right they are not the same version, that's my fault. Thank you for pointing it out. I will make a new `pip` release later today.

Did you end up cloning the repository? Is everything working for you now?

**Comment by ilyasst** [comment]
I ended up cloning the repository after installing the pip version, everything worked fine after that. 
I got an issue with IEEE that I could not get to work with my api_key, but I did not spend that much time trying to fix that yet.
Another thing that is not super clear to me is how to gather large amounts (hundreds and hundreds) of publications without hitting the 504 error ...

**Comment by Nikoleta-v3** [comment]
Thanks again for your issue. The new release is now out. 

The way that I collected data was to ask for 10 articles per request and iterate over the `start` argument. There were times that I did hit a 504 error and just waited for a day or so before I starting again.

That being said there this library:https://pypi.org/project/ratelimit/ which has a function decorator preventing a function from being called more often than that allowed by the API provider. But you need to know what the rules are for the specific APIs and I am afraid I do not know remember.

I read you blog post and it was a really good read! It's unfortunate that not all providers have contain information on whether the article is open access or not.
